#:schema node_modules/wrangler/config-schema.json
name = "shrtn"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "shrtn_redirects"
id = ""

[[kv_namespaces]]
binding = "shrtn_redirects_rev"
id = ""

[[kv_namespaces]]
binding = "shrtn_config"
id = ""